services:
  openid-provider:
    build:
      context: ../op
      dockerfile: ../op/Dockerfile
    image: openid-provider
    ports:
        - 8080:8080
  relying-party:
    build:
      context: ../rp
      dockerfile: ../rp/Dockerfile
    image: relying-party
    depends_on:
      - openid-provider
    ports:
      - 8081:8081
